Feature/effect spec helpers
TheEmidee/UE4GASExtensions pull request #15
Opened 2021-11-04 19:07 UTC by VectorGamez

2021-11-07 14:30 UTC, TheEmidee requested changes

2021-11-07 14:30 UTC, TheEmidee commented on Source/GASExtensions/Public/GASExtAbilitySystemFunctionLibrary.h
> +    static FGameplayEffectContextHandle GetContextHandle( const FGameplayEffectSpec & gameplay_effect_spec );
I'd rename `GetContextHandleFromGameplayEffectSpec`

2021-11-07 14:30 UTC, TheEmidee commented on Source/GASExtensions/Public/GASExtAbilitySystemFunctionLibrary.h
> +    static FGameplayTagContainer GetTargetTagContainer( const FGameplayEffectSpec & gameplay_effect_spec );
I'd rename `GetTargettagContainerFromGameplayEffectSpec`

2021-11-07 14:30 UTC, TheEmidee commented on Source/GASExtensions/Public/GASExtAbilitySystemFunctionLibrary.h
> +    static float GetFloatAttribute( const FGameplayEffectSpec & gameplay_effect_spec, FGameplayAttribute attribute );
I think you should just create a function that returns the effect causer. Getting a float attribute from it already exists

2021-11-09 16:24 UTC, TheEmidee approved these changes

2021-11-09 16:24 UTC, merged

2021-11-09 16:26 UTC, VectorGamez commented on Source/GASExtensions/Public/GASExtAbilitySystemFunctionLibrary.h
> +    static float GetFloatAttribute( const FGameplayEffectSpec & gameplay_effect_spec, FGameplayAttribute attribute );
We can also get the effect causer from the context already. That makes us able to just remove this function.

2021-11-09 16:26 UTC, VectorGamez commented on Source/GASExtensions/Public/GASExtAbilitySystemFunctionLibrary.h
> +    static FGameplayTagContainer GetTargetTagContainer( const FGameplayEffectSpec & gameplay_effect_spec );
Done

2021-11-09 16:26 UTC, VectorGamez commented on Source/GASExtensions/Public/GASExtAbilitySystemFunctionLibrary.h
> +    static FGameplayEffectContextHandle GetContextHandle( const FGameplayEffectSpec & gameplay_effect_spec );
Done.