feature/gameplay_effect_container_improvements
TheEmidee/UE4GASExtensions pull request #19
Opened 2021-12-06 14:39 UTC by VectorGamez

2021-12-07 11:25 UTC, TheEmidee requested changes

2021-12-07 11:25 UTC, TheEmidee commented on Source/GASExtensions/Public/GASExtAbilityTypesBase.h
> +    UPROPERTY( EditAnywhere, BlueprintReadOnly, Category = "GameplayEffectContainerSpec" )
EditAnywhere can be removed on all the properties

2021-12-08 11:35 UTC, VectorGamez commented on Source/GASExtensions/Public/GASExtAbilityTypesBase.h
> +    UPROPERTY( EditAnywhere, BlueprintReadOnly, Category = "GameplayEffectContainerSpec" )
Done.

2021-12-08 11:36 UTC, TheEmidee approved these changes

2021-12-08 11:36 UTC, merged