Feature/gas actor
TheEmidee/UE4GASExtensions pull request #32
Opened 2022-02-24 17:34 UTC by VectorGamez

2022-02-24 21:28 UTC, TheEmidee requested changes

2022-02-24 21:28 UTC, TheEmidee commented on Source/GASExtensions/Private/Abilities/GASExtGameplayAbility.cpp
> +    return 0;
return INDEX_NONE instead

2022-02-25 09:27 UTC, VectorGamez commented on Source/GASExtensions/Private/Abilities/GASExtGameplayAbility.cpp
> +    return 0;
Done.

2022-02-25 09:30 UTC, TheEmidee approved these changes

2022-02-25 09:31 UTC, merged