feature/gameplay_feature_action_grant
TheEmidee/UE4GASExtensions pull request #35
Opened 2022-04-12 15:33 UTC by TheEmidee

Implemented GASExtGameFeatureAction_Grant

2022-04-12 16:41 UTC, VectorGamez approved these changes

2022-04-13 08:25 UTC, VectorGamez requested changes

2022-04-13 08:25 UTC, VectorGamez commented on Source/GASExtensions/Private/GameFeatures/GASExtGameFeatureAction_Grant.cpp
> +                TSubclassOf< UAttributeSet > attribute_set_class = attributes.AttributeSetType.LoadSynchronous();
auto + cast

2022-04-13 08:25 UTC, VectorGamez commented on Source/GASExtensions/Private/GameFeatures/GASExtGameFeatureAction_Grant.cpp
> +                TSubclassOf< UGameplayEffect > gameplay_effect_class = effect.LoadSynchronous();
auto + cast

2022-04-13 08:25 UTC, VectorGamez commented on Source/GASExtensions/Private/GameFeatures/GASExtGameFeatureAction_Grant.cpp
> +            const TSharedPtr< FComponentRequestHandle > request_handle = component_manager->AddComponentRequest( abilities_entry.ActorClass, component_type );
auto

2022-04-13 15:41 UTC, TheEmidee commented on Source/GASExtensions/Private/GameFeatures/GASExtGameFeatureAction_Grant.cpp
> +            const TSharedPtr< FComponentRequestHandle > request_handle = component_manager->AddComponentRequest( abilities_entry.ActorClass, component_type );
done

2022-04-13 15:41 UTC, TheEmidee commented on Source/GASExtensions/Private/GameFeatures/GASExtGameFeatureAction_Grant.cpp
> +                TSubclassOf< UGameplayEffect > gameplay_effect_class = effect.LoadSynchronous();
not needed there's an implicit conversion

2022-04-13 15:42 UTC, TheEmidee commented on Source/GASExtensions/Private/GameFeatures/GASExtGameFeatureAction_Grant.cpp
> +                TSubclassOf< UAttributeSet > attribute_set_class = attributes.AttributeSetType.LoadSynchronous();
not needed there's an implicit conversion (and it's easier to read than a cast IMO)

2022-04-14 07:14 UTC, VectorGamez approved these changes

2022-04-14 07:46 UTC, merged